---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dsws

<!-- badges: start -->
<!-- badges: end -->

The goal of dsws is to be used as workshop material organized by GoodJob! data science team.


## Installation

You can install the development version of dsws from [GitHub](https://github.com/GoodJobTech/ds-ws) with:

``` r
# install.packages("devtools")
devtools::install_github("GoodJobTech/ds-ws")
```

## Example

Lets import workshop library.

```{r example}
library(dsws)
## basic example code
```

Lets check included data, starting with the odds file

```{r}
summary(dsws::odds_table)
```

Lets check test data scores

```{r}
summary(dsws::scores)
```

Lets check train data

```{r}
summary(dsws::train_data)
```

Lets bet randomly
```{r}
set.seed(4)
random_play_vector <- sample(c(0,1), replace=TRUE, size=nrow(odds_table))
score_the_play_vector(random_play_vector, scores = dsws::scores, odds_table = dsws::odds_table)

```
